### ISSUE TITLE
Missing keypoints

### ISSUE THREAD

**Issue by moshanATucsd** [krrish94/ICRA2017#2]
Hi, when we could not detect all the 36 keypoints, say keypoint no. 1 is not detected when we are supposed to see it according to the azimuth, should we force the visibility to 0? It does not seem to make a difference by changing the visibility, the output shape will be wrong. It seems that the shape optimization will always use some fixed set of keypoints. Is there a way to work around the missing detections?

Maybe the only way is that we should infer the position of keypoint no. 1 based on the keypoints we have detected? Then in that case we have to always generate 36 keypoint positions?

**Comment by krrish94** [comment]
Instead of forcing visibility to 0, I would rather set it to a low, but nonzero value. This provides scope for the optimzer to get a good shape/pose estimate using that keypoint (if it is indeed deemed an inlier according to the M-estimators in place).

In short, yes, you need to provide all the keypoints for each image, regardless of whether or not they're visible. The keypoints provided could be erroneous; that's another issue, and the optimizer takes it into account to a great extent.

**Comment by moshanATucsd** [comment]
Thanks for the reply! It seems that when few keypoints are detected, say only 7 keypoints are detected correctly out of 36, then the shape optimization will fail due to a lack of constraints. Is there a minimum number of reliable detections for the optimization to work well? Moreover, is it possible to modify it so that it also works with only few detections?

**Comment by krrish94** [comment]
Your remarks are right. Since shape and pose adjustment are nonlinear optimization problems, just like bundle adjustment, they need a good initialization to converge to a good solution. In practice, I think it works well when ~10 keypoints are well-detected, and the viewpoint guess is to within 15 degrees of the true viewpoint. This is only an average estimate, and there could be cases where the viewpoint guess is very precise, but some keypoint localization error degrades optimization, and so on.

The way we've baked in fault-tolerance into our system is by means of using M-estimators. If you feel your outlier ratio is higher than usual, you might have to tweak the parameters of `ceres::HuberLoss` in `ceresCode/singleViewPoseAdjuster.cc` and `ceresCode/singleViewShapeAdjuster.cc`.

**Comment by moshanATucsd** [comment]
Let's say the pose estimation is somewhat correct, but shape estimation fails due to the lack of detected keypoints, then should we decrease the threshold in `problem.AddResidualBlock(lambdaError, new ceres::HuberLoss(0.5), rotAngleAxis, lambdas)` and `problem.AddResidualBlock(lambdaRegularizer, new ceres::HuberLoss(0.1), lambdas)`? I did that but the results don't seem to change much...

**Comment by krrish94** [comment]
That's about right. One aspect that we did for the paper, but not in the demo code was to iterate pose and shape adjustment steps 2-3 times. I would be interested to know what kind of data you're trying it on. As long as you keep changing the initial `lambdas` (which are always constant in the demo code), you should be fine.

**Comment by moshanATucsd** [comment]
Thanks for the advice! I am also using images from KITTI but the keypoint detections are not good due to occlusion/shadows etc. I have tried very small values such as HuberLoss(0.01) but still have no luck. Is there a range of HuberLoss values we should try when we only have ~7 good keypoint detections?

**Comment by krrish94** [comment]
Sometimes, even increasing the threshold helps. It all depends on how your error magnitudes are.

And, I'm kinda surprised you have only about 7 good keypoint detections, if you're using the same keypoint network I mentioned in the README. I suspect you're trying on far-off cars whose images are blurred?

If it helps, I'm happy to do another pass of the demo script early next week. That's when I intend to add a few more performance hacks and visualization code.

**Comment by Haotian-Zhang** [comment]
Hi @krrish94, I'm kinda into your way of visualization of your camera pose and point cloud. Are all the visualization are programmed and generated using Python too? If they are, could you also please tell me which library you are referring to?

**Comment by krrish94** [comment]
That's unfortunately in a Matlab version we used, during submission. However, I'd be happy to share that code with you. PM.
